/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.form.onboarding.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.form.onboarding.model.OBFormFieldMapping;
import com.liferay.form.onboarding.model.OBFormFieldMappingModel;
import com.liferay.form.onboarding.model.OBFormFieldMappingSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OBFormFieldMapping service. Represents a row in the &quot;OBForm_OBFormFieldMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OBFormFieldMappingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OBFormFieldMappingImpl}.
 * </p>
 *
 * @author Evan Thibodeau
 * @see OBFormFieldMappingImpl
 * @generated
 */
@JSON(strict = true)
public class OBFormFieldMappingModelImpl
	extends BaseModelImpl<OBFormFieldMapping>
	implements OBFormFieldMappingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ob form field mapping model instance should use the <code>OBFormFieldMapping</code> interface instead.
	 */
	public static final String TABLE_NAME = "OBForm_OBFormFieldMapping";

	public static final Object[][] TABLE_COLUMNS = {
		{"obFormFieldId", Types.BIGINT}, {"userPropertyName", Types.VARCHAR},
		{"formFieldId", Types.BIGINT}, {"obFormEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("obFormFieldId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userPropertyName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("formFieldId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("obFormEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OBForm_OBFormFieldMapping (obFormFieldId LONG not null primary key,userPropertyName VARCHAR(75) null,formFieldId LONG,obFormEntryId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table OBForm_OBFormFieldMapping";

	public static final String ORDER_BY_JPQL =
		" ORDER BY obFormFieldMapping.obFormFieldId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OBForm_OBFormFieldMapping.obFormFieldId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long OBFORMENTRYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long OBFORMFIELDID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static OBFormFieldMapping toModel(OBFormFieldMappingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OBFormFieldMapping model = new OBFormFieldMappingImpl();

		model.setObFormFieldId(soapModel.getObFormFieldId());
		model.setUserPropertyName(soapModel.getUserPropertyName());
		model.setFormFieldId(soapModel.getFormFieldId());
		model.setObFormEntryId(soapModel.getObFormEntryId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<OBFormFieldMapping> toModels(
		OBFormFieldMappingSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<OBFormFieldMapping> models = new ArrayList<OBFormFieldMapping>(
			soapModels.length);

		for (OBFormFieldMappingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public OBFormFieldMappingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _obFormFieldId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setObFormFieldId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _obFormFieldId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OBFormFieldMapping.class;
	}

	@Override
	public String getModelClassName() {
		return OBFormFieldMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OBFormFieldMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OBFormFieldMapping, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OBFormFieldMapping, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((OBFormFieldMapping)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OBFormFieldMapping, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OBFormFieldMapping, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OBFormFieldMapping)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OBFormFieldMapping, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OBFormFieldMapping, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, OBFormFieldMapping>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			OBFormFieldMapping.class.getClassLoader(), OBFormFieldMapping.class,
			ModelWrapper.class);

		try {
			Constructor<OBFormFieldMapping> constructor =
				(Constructor<OBFormFieldMapping>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<OBFormFieldMapping, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OBFormFieldMapping, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OBFormFieldMapping, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<OBFormFieldMapping, Object>>();
		Map<String, BiConsumer<OBFormFieldMapping, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<OBFormFieldMapping, ?>>();

		attributeGetterFunctions.put(
			"obFormFieldId", OBFormFieldMapping::getObFormFieldId);
		attributeSetterBiConsumers.put(
			"obFormFieldId",
			(BiConsumer<OBFormFieldMapping, Long>)
				OBFormFieldMapping::setObFormFieldId);
		attributeGetterFunctions.put(
			"userPropertyName", OBFormFieldMapping::getUserPropertyName);
		attributeSetterBiConsumers.put(
			"userPropertyName",
			(BiConsumer<OBFormFieldMapping, String>)
				OBFormFieldMapping::setUserPropertyName);
		attributeGetterFunctions.put(
			"formFieldId", OBFormFieldMapping::getFormFieldId);
		attributeSetterBiConsumers.put(
			"formFieldId",
			(BiConsumer<OBFormFieldMapping, Long>)
				OBFormFieldMapping::setFormFieldId);
		attributeGetterFunctions.put(
			"obFormEntryId", OBFormFieldMapping::getObFormEntryId);
		attributeSetterBiConsumers.put(
			"obFormEntryId",
			(BiConsumer<OBFormFieldMapping, Long>)
				OBFormFieldMapping::setObFormEntryId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getObFormFieldId() {
		return _obFormFieldId;
	}

	@Override
	public void setObFormFieldId(long obFormFieldId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_obFormFieldId = obFormFieldId;
	}

	@JSON
	@Override
	public String getUserPropertyName() {
		if (_userPropertyName == null) {
			return "";
		}
		else {
			return _userPropertyName;
		}
	}

	@Override
	public void setUserPropertyName(String userPropertyName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userPropertyName = userPropertyName;
	}

	@JSON
	@Override
	public long getFormFieldId() {
		return _formFieldId;
	}

	@Override
	public void setFormFieldId(long formFieldId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_formFieldId = formFieldId;
	}

	@JSON
	@Override
	public long getObFormEntryId() {
		return _obFormEntryId;
	}

	@Override
	public void setObFormEntryId(long obFormEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_obFormEntryId = obFormEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalObFormEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("obFormEntryId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, OBFormFieldMapping.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OBFormFieldMapping toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OBFormFieldMapping>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OBFormFieldMappingImpl obFormFieldMappingImpl =
			new OBFormFieldMappingImpl();

		obFormFieldMappingImpl.setObFormFieldId(getObFormFieldId());
		obFormFieldMappingImpl.setUserPropertyName(getUserPropertyName());
		obFormFieldMappingImpl.setFormFieldId(getFormFieldId());
		obFormFieldMappingImpl.setObFormEntryId(getObFormEntryId());

		obFormFieldMappingImpl.resetOriginalValues();

		return obFormFieldMappingImpl;
	}

	@Override
	public int compareTo(OBFormFieldMapping obFormFieldMapping) {
		long primaryKey = obFormFieldMapping.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OBFormFieldMapping)) {
			return false;
		}

		OBFormFieldMapping obFormFieldMapping = (OBFormFieldMapping)object;

		long primaryKey = obFormFieldMapping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<OBFormFieldMapping> toCacheModel() {
		OBFormFieldMappingCacheModel obFormFieldMappingCacheModel =
			new OBFormFieldMappingCacheModel();

		obFormFieldMappingCacheModel.obFormFieldId = getObFormFieldId();

		obFormFieldMappingCacheModel.userPropertyName = getUserPropertyName();

		String userPropertyName = obFormFieldMappingCacheModel.userPropertyName;

		if ((userPropertyName != null) && (userPropertyName.length() == 0)) {
			obFormFieldMappingCacheModel.userPropertyName = null;
		}

		obFormFieldMappingCacheModel.formFieldId = getFormFieldId();

		obFormFieldMappingCacheModel.obFormEntryId = getObFormEntryId();

		return obFormFieldMappingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OBFormFieldMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OBFormFieldMapping, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OBFormFieldMapping, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((OBFormFieldMapping)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<OBFormFieldMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<OBFormFieldMapping, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OBFormFieldMapping, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((OBFormFieldMapping)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OBFormFieldMapping>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _obFormFieldId;
	private String _userPropertyName;
	private long _formFieldId;
	private long _obFormEntryId;

	public <T> T getColumnValue(String columnName) {
		Function<OBFormFieldMapping, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((OBFormFieldMapping)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("obFormFieldId", _obFormFieldId);
		_columnOriginalValues.put("userPropertyName", _userPropertyName);
		_columnOriginalValues.put("formFieldId", _formFieldId);
		_columnOriginalValues.put("obFormEntryId", _obFormEntryId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("obFormFieldId", 1L);

		columnBitmasks.put("userPropertyName", 2L);

		columnBitmasks.put("formFieldId", 4L);

		columnBitmasks.put("obFormEntryId", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private OBFormFieldMapping _escapedModel;

}