/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.form.onboarding.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the OBFormEntry service. Represents a row in the &quot;OBForm_OBFormEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.form.onboarding.model.impl.OBFormEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.form.onboarding.model.impl.OBFormEntryImpl</code>.
 * </p>
 *
 * @author Evan Thibodeau
 * @see OBFormEntry
 * @generated
 */
@ProviderType
public interface OBFormEntryModel
	extends BaseModel<OBFormEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ob form entry model instance should use the {@link OBFormEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this ob form entry.
	 *
	 * @return the primary key of this ob form entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ob form entry.
	 *
	 * @param primaryKey the primary key of this ob form entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ob form entry.
	 *
	 * @return the uuid of this ob form entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ob form entry.
	 *
	 * @param uuid the uuid of this ob form entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ob form entry ID of this ob form entry.
	 *
	 * @return the ob form entry ID of this ob form entry
	 */
	public long getObFormEntryId();

	/**
	 * Sets the ob form entry ID of this ob form entry.
	 *
	 * @param obFormEntryId the ob form entry ID of this ob form entry
	 */
	public void setObFormEntryId(long obFormEntryId);

	/**
	 * Returns the group ID of this ob form entry.
	 *
	 * @return the group ID of this ob form entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ob form entry.
	 *
	 * @param groupId the group ID of this ob form entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ob form entry.
	 *
	 * @return the company ID of this ob form entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ob form entry.
	 *
	 * @param companyId the company ID of this ob form entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ob form entry.
	 *
	 * @return the user ID of this ob form entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ob form entry.
	 *
	 * @param userId the user ID of this ob form entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ob form entry.
	 *
	 * @return the user uuid of this ob form entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ob form entry.
	 *
	 * @param userUuid the user uuid of this ob form entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ob form entry.
	 *
	 * @return the user name of this ob form entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ob form entry.
	 *
	 * @param userName the user name of this ob form entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ob form entry.
	 *
	 * @return the create date of this ob form entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ob form entry.
	 *
	 * @param createDate the create date of this ob form entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ob form entry.
	 *
	 * @return the modified date of this ob form entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ob form entry.
	 *
	 * @param modifiedDate the modified date of this ob form entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this ob form entry.
	 *
	 * @return the name of this ob form entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this ob form entry.
	 *
	 * @param name the name of this ob form entry
	 */
	public void setName(String name);

	/**
	 * Returns the form ID of this ob form entry.
	 *
	 * @return the form ID of this ob form entry
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this ob form entry.
	 *
	 * @param formId the form ID of this ob form entry
	 */
	public void setFormId(long formId);

	/**
	 * Returns the organization IDs of this ob form entry.
	 *
	 * @return the organization IDs of this ob form entry
	 */
	@AutoEscape
	public String getOrganizationIds();

	/**
	 * Sets the organization IDs of this ob form entry.
	 *
	 * @param organizationIds the organization IDs of this ob form entry
	 */
	public void setOrganizationIds(String organizationIds);

	/**
	 * Returns the role IDs of this ob form entry.
	 *
	 * @return the role IDs of this ob form entry
	 */
	@AutoEscape
	public String getRoleIds();

	/**
	 * Sets the role IDs of this ob form entry.
	 *
	 * @param roleIds the role IDs of this ob form entry
	 */
	public void setRoleIds(String roleIds);

	/**
	 * Returns the site IDs of this ob form entry.
	 *
	 * @return the site IDs of this ob form entry
	 */
	@AutoEscape
	public String getSiteIds();

	/**
	 * Sets the site IDs of this ob form entry.
	 *
	 * @param siteIds the site IDs of this ob form entry
	 */
	public void setSiteIds(String siteIds);

	/**
	 * Returns the user group IDs of this ob form entry.
	 *
	 * @return the user group IDs of this ob form entry
	 */
	@AutoEscape
	public String getUserGroupIds();

	/**
	 * Sets the user group IDs of this ob form entry.
	 *
	 * @param userGroupIds the user group IDs of this ob form entry
	 */
	public void setUserGroupIds(String userGroupIds);

	/**
	 * Returns the send email of this ob form entry.
	 *
	 * @return the send email of this ob form entry
	 */
	public boolean getSendEmail();

	/**
	 * Returns <code>true</code> if this ob form entry is send email.
	 *
	 * @return <code>true</code> if this ob form entry is send email; <code>false</code> otherwise
	 */
	public boolean isSendEmail();

	/**
	 * Sets whether this ob form entry is send email.
	 *
	 * @param sendEmail the send email of this ob form entry
	 */
	public void setSendEmail(boolean sendEmail);

	/**
	 * Returns the active of this ob form entry.
	 *
	 * @return the active of this ob form entry
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this ob form entry is active.
	 *
	 * @return <code>true</code> if this ob form entry is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this ob form entry is active.
	 *
	 * @param active the active of this ob form entry
	 */
	public void setActive(boolean active);

}