/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.form.onboarding.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the OBFormFieldMapping service. Represents a row in the &quot;OBForm_OBFormFieldMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.form.onboarding.model.impl.OBFormFieldMappingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.form.onboarding.model.impl.OBFormFieldMappingImpl</code>.
 * </p>
 *
 * @author Evan Thibodeau
 * @see OBFormFieldMapping
 * @generated
 */
@ProviderType
public interface OBFormFieldMappingModel extends BaseModel<OBFormFieldMapping> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ob form field mapping model instance should use the {@link OBFormFieldMapping} interface instead.
	 */

	/**
	 * Returns the primary key of this ob form field mapping.
	 *
	 * @return the primary key of this ob form field mapping
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ob form field mapping.
	 *
	 * @param primaryKey the primary key of this ob form field mapping
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ob form field ID of this ob form field mapping.
	 *
	 * @return the ob form field ID of this ob form field mapping
	 */
	public long getObFormFieldId();

	/**
	 * Sets the ob form field ID of this ob form field mapping.
	 *
	 * @param obFormFieldId the ob form field ID of this ob form field mapping
	 */
	public void setObFormFieldId(long obFormFieldId);

	/**
	 * Returns the user property name of this ob form field mapping.
	 *
	 * @return the user property name of this ob form field mapping
	 */
	@AutoEscape
	public String getUserPropertyName();

	/**
	 * Sets the user property name of this ob form field mapping.
	 *
	 * @param userPropertyName the user property name of this ob form field mapping
	 */
	public void setUserPropertyName(String userPropertyName);

	/**
	 * Returns the form field ID of this ob form field mapping.
	 *
	 * @return the form field ID of this ob form field mapping
	 */
	public long getFormFieldId();

	/**
	 * Sets the form field ID of this ob form field mapping.
	 *
	 * @param formFieldId the form field ID of this ob form field mapping
	 */
	public void setFormFieldId(long formFieldId);

	/**
	 * Returns the ob form entry ID of this ob form field mapping.
	 *
	 * @return the ob form entry ID of this ob form field mapping
	 */
	public long getObFormEntryId();

	/**
	 * Sets the ob form entry ID of this ob form field mapping.
	 *
	 * @param obFormEntryId the ob form entry ID of this ob form field mapping
	 */
	public void setObFormEntryId(long obFormEntryId);

}